name: 更新 WakaTime 状态
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 更新 gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: f3c462228680aa45424de3c672c07234
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
